[FEAT/seminar4] 필수과제
DO-SOPT-ANDROID/minjeong-kim pull request #11
Opened 2023-11-17 14:56 UTC by emjayMJkim

## ✍️ Work Description

- 로그인/회원가입 구현
- Follower List 구현 

## 📸 ScreenShot

https://github.com/DO-SOPT-ANDROID/minjeong-kim/assets/128988935/faf85ac2-6fee-4732-8840-07ef9ebd5702

## 🍀 Issues

## ✔️ PR point

- follower list는 follower fragment를 따로 만들어 구현했습니다
- 아시다시피.. 노트북 고장 이슈로ㅜ 처음부터 급하게 다시 하느라 코드 정리 안 된 부분이 있을 수도 있습니다...

2023-11-17 15:12 UTC, Jokwanhee reviewed
노트북 억까해결하느라 고생하셨습니다! 열정 대단하시네요! 🔥

2023-11-17 15:12 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/data/datasource/remote/Impl/AuthDataSourceImpl.kt
> +class AuthDataSourceImpl @Inject constructor(
Hilt 좋네요.. 그냥 저렇게 하면 프로퍼티로 AuthService 쑉 들어가나요?

2023-11-17 15:12 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/di/ApiModule.kt
> +        retrofit.create(AuthService::class.java)
사기다.. Hilt 짱 좋네요.. 싱글톤 + 종속 항목 주입... 저도 써보고 싶네요 ㅠㅠ 민정님 코드를 슥삭해야겠어요 ㅎ_ㅎ

2023-11-17 15:12 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/di/DataSourceModule.kt
> +    @Binds
Binds 라는 어노테이션은 어떤 의미에서 사용되나요?

2023-11-17 15:12 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/signUp/SignUpViewModel.kt
> +    val mbti: MutableLiveData<String> = MutableLiveData()
이 친구들을 LiveData 로 선언해준 이유가 뭔가요 ?_?

2023-11-17 16:52 UTC, taeheeL reviewed
노트북 억까.. 고생했다 민정아 ㅎㅎ

2023-11-17 16:52 UTC, taeheeL commented on app/src/main/java/org/sopt/dosopttemplate/data/repository/Impl/AuthRepositoryImpl.kt
> +        Log.d("auth repository: ", "실패")
Result 타입의 확장 함수인 fold를 사용해보는 건 어떨까요?

2023-11-19 07:17 UTC, KwakEuiJin requested changes
굳굳 리뷰 확인 후 수정 부탁드려요~!!

2023-11-19 07:17 UTC, kez-lab commented on app/src/main/java/org/sopt/dosopttemplate/data/datasource/remote/Impl/FollowerDataSourceImpl.kt
> +}
mapping함수를 따로 만들어 보는 것은 어떨까요?

2023-11-19 07:17 UTC, kez-lab commented on app/src/main/java/org/sopt/dosopttemplate/data/service/FollowerService.kt
> +    suspend fun getFollowerList(
?는 쿼리 어노테이션이 처리해줄거여서 없어도 됩니다~!!

2023-11-19 07:17 UTC, kez-lab commented on app/src/main/java/org/sopt/dosopttemplate/di/Qualifier.kt
> +annotation class ReqresRetrofit
👍

2023-11-19 07:17 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/follower/FollowerFragment.kt
> +    private lateinit var followerAdapter: FollowerAdapter
어댑터도 null 처리를 통해 리소스 해제를 해주는 것이 메모리 누수 방지 차원에서 좋을 것 같습니다

2023-11-19 07:17 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/logIn/LogInActivity.kt
> +//    }
🥲

2023-11-19 14:50 UTC, yeonjeen reviewed
어려운 상황에서 과제하느라 수고 많으셨습니다~ 가독성 부분에서 좋았던 점이 많아서 다음 과제에서 저도 많이 참고하겠습니당!!

2023-11-19 14:50 UTC, yeonjeen commented on app/src/main/java/org/sopt/dosopttemplate/data/repository/AuthRepository.kt
> +}
저는 파일을 다 따로만들었는데 확실히 이렇게 같은 파일에 있는게 더 좋은 것 같아요..!

2023-11-19 14:50 UTC, yeonjeen commented on app/src/main/java/org/sopt/dosopttemplate/di/RetrofitModule.kt
> +}
provideReqresRetrofit()랑 비슷한 코드 부분이 많은데 중복되는 부분을 함수화 시킬 수도 있을까요?

2023-11-29 05:35 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/di/DataSourceModule.kt
> +    @Binds
인터페이스는 생성자를 삽입할 수 없어서, 인터페이스를 삽입할 때는 Hilt 모듈 내에 @Binds로 어노테이션을 지정해 주입해 줄 수 있습니다!!

2023-11-29 05:39 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/presentation/signUp/SignUpViewModel.kt
> +    val mbti: MutableLiveData<String> = MutableLiveData()
사실.. 양방향 데이터바인딩으로 id/pw 에러를 보여주려고 했으나.. 시간 문제로 이번에 하려고 합니당

2023-11-29 05:44 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/data/repository/Impl/AuthRepositoryImpl.kt
> +        Log.d("auth repository: ", "실패")
오 감사합니다 적용해보겠습니당!

2023-11-29 12:12 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/data/datasource/remote/Impl/FollowerDataSourceImpl.kt
> +}
넵 수정했습니당

2023-11-29 13:30 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/follower/FollowerFragment.kt
> +    private lateinit var followerAdapter: FollowerAdapter
네넵 수정했습니당

2023-11-30 09:29 UTC, KwakEuiJin approved these changes

2023-11-30 10:19 UTC, merged