[FEAT/seminar1] 필수과제
DO-SOPT-ANDROID/minjeong-kim pull request #2
Opened 2023-10-11 20:26 UTC by emjayMJkim

## ✍️ Work Description

- [x] 로그인 페이지
- [x] 회원가입 페이지
- [x] 메인 페이지

 
## 📸 ScreenShot

https://github.com/DO-SOPT-ANDROID/minjeong-kim/assets/128988935/1bbcda90-f068-4ee2-ba46-2582941d4a2a

## 🍀 Issues

#1 

## ✔️ PR point

2023-10-12 00:24 UTC, KwakEuiJin requested changes
역시 민정님 코드 믿고 봤습니다 과제하느라 고생 많으셨습니다 🎨
리뷰 보시고 수정 부탁드려요

2023-10-12 00:24 UTC, KwakEuiJin commented on app/build.gradle
> +    implementation 'com.google.android.material:material:1.10.0'
혹시 안드로이드 버전 몇 쓰시나요?! (그냥 궁굼ㅎ)

2023-10-12 00:24 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/logIn/LogInActivity.kt
> +                userData = result.data?.getParcelable(USER_DATA, UserData::class.java)!!
!!(unSafeCall) 보다는 널체크가 필요할 것 같습니다

2023-10-12 00:24 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/signUp/SignUpActivity.kt
> +        finish()
scope 함수 활용 좋아요~!!

2023-10-12 00:24 UTC, KwakEuiJin commented on app/src/main/res/layout/activity_login.xml
> +            app:layout_constraintStart_toStartOf="parent" />
하나의 id를 기준으로 잡아서 start or end를 정의하면 각 뷰마다 margin을 걸어주지 않아도 됩니다!

2023-10-12 00:24 UTC, KwakEuiJin commented on app/src/main/res/layout/activity_signup.xml
> +            app:layout_constraintBottom_toBottomOf="parent" />
match_parent 보다는 0dp (match_constraint)를 쓰시는 습관을 기르시면 추 후 유연한 레이아웃 개발에 도움이 되실겁니다

2023-10-12 02:49 UTC, Jokwanhee reviewed
민정님 깔끔한 코드보고 감탄합니다.. 🙇

2023-10-12 02:49 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/logIn/LogInActivity.kt
> +        resultLauncher = registerForActivityResult(
Activity Result API 를 전역 변수로 값을 할당하는 것이 아닌 함수 내부에서 할당하는 이유가 따로 있나요?

2023-10-12 02:49 UTC, Jokwanhee commented on app/src/main/res/layout/activity_main.xml
> +            <androidx.appcompat.widget.AppCompatImageView
ImageView 대신 AppCompatImageView를 사용하신 이유가 있나요?

2023-10-12 17:56 UTC, emjayMJkim commented on app/build.gradle
> +    implementation 'com.google.android.material:material:1.10.0'
플라밍고 2022.2.1.20 버전 쓰고 있습니다

2023-10-12 17:56 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/presentation/logIn/LogInActivity.kt
> +                userData = result.data?.getParcelable(USER_DATA, UserData::class.java)!!
수정했습니다!!

2023-10-12 17:58 UTC, emjayMJkim commented on app/src/main/res/layout/activity_signup.xml
> +            app:layout_constraintBottom_toBottomOf="parent" />
감사합니다 수정했습니당

2023-10-12 18:00 UTC, emjayMJkim commented on app/src/main/res/layout/activity_main.xml
> +            <androidx.appcompat.widget.AppCompatImageView
플랫폼 버전 상관 없이 어느 버전에서나 똑같이 구현할 수 있습니다. 다만, 사실 롤리팝 이전 버전을 쓰는 경우는 별로 없으니 굳이 사용할 필요성은 없다고 생각이 듭니다..

2023-10-12 18:03 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/presentation/logIn/LogInActivity.kt
> +        resultLauncher = registerForActivityResult(
함수화 습관 때문에...ㅎㅎ 좀 더 깔끔해 보이는 것 같다고 생각했습니다

2023-10-13 04:59 UTC, yeonjeen reviewed
저와 같은 기능을 구현한 코드를 보았을 때 훨씬 간결하고 깔끔하다는 느낌을 많이 받았습니다!! 덕분에 아주 많이 참고 할 수 있었어용:)

2023-10-13 04:59 UTC, yeonjeen commented on app/src/main/java/org/sopt/dosopttemplate/presentation/logIn/LogInActivity.kt
> +    }
메시지를 이렇게 표현할 수도 있네요!! Toast.makeText 사용 할 때보다 훨씬 간결해 보여요! 이렇게 표현했을 때 어떤 차이가 있나요?

2023-10-13 04:59 UTC, yeonjeen commented on app/src/main/java/org/sopt/dosopttemplate/presentation/signUp/SignUpActivity.kt
> +        with (binding) {
scope 함수는 코드리뷰 하면서 처음 접했는데 with를 사용한 이유는 뭔가요??

2023-10-14 08:50 UTC, KwakEuiJin approved these changes

2023-10-15 14:50 UTC, merged