[FEAT/seminar2] 필수과제
DO-SOPT-ANDROID/minjeong-kim pull request #4
Opened 2023-10-26 07:50 UTC by emjayMJkim

## ✍️ Work Description

- [x] 홈 탭: 내 프로필, 친구 프로필 Multi-View Type RecyclerView 
- [x] 마이페이지 탭: 마이페이지 

## 📸 ScreenShot

https://github.com/DO-SOPT-ANDROID/minjeong-kim/assets/128988935/72f14505-dde0-4c02-8122-a18a2e8e9ae8

## 🍀 Issues

#3 

## ✔️ PR point

- 아직 자동로그인 구현을 안한 관계로.. 로그인부터 영상 찍었습니다
- 시험 끝나고 리팩할께요 ㅎㅎ

2023-10-27 01:48 UTC, Jokwanhee reviewed
시험기간인데 고생하셨습니다! 잘 보고 갑니다 🐰

2023-10-27 01:48 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/home/HomeViewModel.kt
> +    private val _mockProfileList = listOf<Profile>(
지브리 좋아하시나봐요! 이번에 미야자키 하야오 마지막 작품 보시나요?

2023-10-27 01:48 UTC, Jokwanhee commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseFragment.kt
> +abstract class BaseFragment<B : ViewDataBinding>(@LayoutRes private val layoutResId: Int) :
그때 세미나에서 의진님이 말씀해주신 Fragment 생성자 이슈가 여기서도 발생하나요? 발생한다면, 리소스파일 id 프로퍼티를 클래스 내 추상 멤버변수로 정의하면 어떨까요?

2023-10-27 08:15 UTC, KwakEuiJin requested changes
2주차 과제하시느라 고생하셨습니다~!! 코멘트 확인 후 수정 부탁드립니다

2023-10-27 08:15 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseFragment.kt
> +abstract class BaseFragment<B : ViewDataBinding>(@LayoutRes private val layoutResId: Int) :
네네 Fragment에 생성자 추가하면 상태 변경시 크래시를 발생시킵니다!

2023-10-27 08:15 UTC, KwakEuiJin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/home/HomeViewHolder.kt
> +}
scope 함수를 활용해보는 것도 좋을 것 같습니다~!!

2023-10-31 19:02 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/home/HomeViewHolder.kt
> +}
제가 왜 이렇게 했을까요... 하암..

2023-10-31 19:05 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/base/BaseFragment.kt
> +abstract class BaseFragment<B : ViewDataBinding>(@LayoutRes private val layoutResId: Int) :
감사합니닷..!! 코드 다시 보고 수정했습니다

2023-10-31 19:06 UTC, emjayMJkim commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/home/HomeViewModel.kt
> +    private val _mockProfileList = listOf<Profile>(
당연히 보러 가야죠 ㅎㅎ

2023-11-01 00:53 UTC, KwakEuiJin approved these changes
LGTM

2023-11-01 01:05 UTC, merged